### ISSUE TITLE
can you provide code for generating occupancy labels from raw point cloud?

### ISSUE THREAD

**Issue by poodarchu** [Tsinghua-MARS-Lab/Occ3D#17]

**Comment by xuqinwang** [comment]
Thank you for your excellent work, it could be very helpful if your team can provide code for generating occupancy label so that we can extend occupancy prediction problem to other raw lidar point cloud datasets. Many thanks!

**Comment by cnstark** [comment]
Waiting for it

**Comment by yhg1010** [comment]
Did you get the code for generating occupancy label? Thanks for your answer!
