### ISSUE TITLE
Are [mask_lidar] and [mask_camera] generated during training in real time?

### ISSUE THREAD

**Issue by ZhihaoWang1997** [Tsinghua-MARS-Lab/Occ3D#2]
I'm curious if  [mask_lidar] and [mask_camera] are generated during training in real time. If not, are many voxels marked as "free" but "visible" saved when when preparing the data?

**Comment by waveleaf27** [comment]
Yep, the mask_lidar/mask_camera is generated specifically for each frame.

**Comment by ZhihaoWang1997** [comment]
Sorry you may have misunderstood me. I was asking if the two masks are generated in advance or in real time when the data is loaded? If they are generated in real time, how is the time efficiency?

**Comment by ZhihaoWang1997** [comment]
Sorry you may have misunderstood what I meant. I was asking if the two masks are generated in advance or in real time when the data is loaded? If they are generated in real time, how is the time efficiency?

**Comment by waveleaf27** [comment]
Both the two masks are generated in advance , you can ref [web](https://tsinghua-mars-lab.github.io/Occ3D/) or [paper](https://arxiv.org/abs/2304.14365) for more detail.
