### ISSUE TITLE
will you release mask_lidar and mask_camera code？

### ISSUE THREAD

**Issue by alexa19lab** [Tsinghua-MARS-Lab/Occ3D#20]
May I ask if you will  release mask_lidar and mask_camera code？ Thanks!

**Comment by waveleaf27** [comment]
At present, the code used for ground-truth (GT) construction will not be released. This decision was made to prevent challenge participants from using scripts to generate their submissions.

**Comment by Daniel-xsy** [comment]
@waveleaf27 Hi, I'm wondering if the code to generate GT is released?
