### ISSUE TITLE
Why the performance for BevFormer in paper is higher than the baseline in cvpr challenge page?

### ISSUE THREAD

**Issue by promesse** [Tsinghua-MARS-Lab/Occ3D#3]
![image](https://github.com/Tsinghua-MARS-Lab/Occ3D/assets/26239060/d933bf6b-2673-4814-b3db-6a607395822e)
![image](https://github.com/Tsinghua-MARS-Lab/Occ3D/assets/26239060/03bccd49-6235-4042-900f-6324a75f7109)

page:https://github.com/CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction/blob/main/docs/getting_started.md

**Comment by waveleaf27** [comment]
Hi, the main reason is adopting more effective training strategies, such as adjusting loss weight and using data augmentation.

**Comment by promesse** [comment]
> Hi, the main reason is adopting more effective training strategies, such as adjusting loss weight and using data augmentation.
Did you use camera_maks during training?

**Comment by waveleaf27** [comment]
We not use camera_mask for the metrics you mentioned.

**Comment by promesse** [comment]
Even for loss？
