### ISSUE TITLE
the meaning of "spatial_shape" in visiblity calculation

### ISSUE THREAD

**Issue by chouscode** [Tsinghua-MARS-Lab/Occ3D#30]
Awesome work ! 
I am confused about the parameter named "spatial_shape" in ray casting method (the parameter can be found in Algorithm1 & 2 & 3) and can't find any explanation in your paper. Would you explain the meaning of this parameter? 
Thanks !

**Comment by chouscode** [comment]
OK,  I see!

**Comment by zhaowenZhou** [comment]
Could you tell me what does spatial_shape mean?
