### ISSUE TITLE
The voxel size in Occ3d-Waymo mentioned in the article is inconsistent with what is stated on the webpage

### ISSUE THREAD

**Issue by Agito555** [Tsinghua-MARS-Lab/Occ3D#35]
I noticed that the voxel size mentioned in the article for Occ-Waymo is 0.05m, which is inconsistent with what you stated on the webpage as [0.1,0.1,0.2]/[0.4,0.4,0.4]. I'm curious to know why this discrepancy exists?

**Comment by andrewcaunes** [comment]
Hello, I don't know why you closed this issue, I was also surprised to see this discrepancy:
In the paper they claim 0.05m voxel size which would be the finest for datasets out there, but then no other mention and only of 0.1m ?
