### ISSUE TITLE
When will the code be released？

### ISSUE THREAD

**Issue by chenzyhust** [Tsinghua-MARS-Lab/Occ3D#4]
The information provided in the paper is not enough, when will the code be released

**Comment by waveleaf27** [comment]
In order to make the code structure complete and readable, it takes some time to organize it. Currently, we only release the dataset and there is no time available to release the code. 
Feel free to contact me if you are in urgent need of the code .

**Comment by chenzyhust** [comment]
Thank you for your reply, it is convenient to provide your email address or other contact information？

**Comment by aoyanl** [comment]
> In order to make the code structure complete and readable, it takes some time to organize it. Currently, we only release the dataset and there is no time available to release the code. Feel free to contact me if you are in urgent need of the code .

Hi，do you plan to release all the code?

**Comment by waveleaf27** [comment]
HI, the code used to generate dataset will NOT been released. For the model and training code, we will release in July.

**Comment by SISTMrL** [comment]
> 

hi, i'm insterested in your work, and in urgent need of the code, due to i want to know the implementation of coarse to fine voxel encoder. And i can't find any contact information of you, so i give my wechat: 15256956711, looking forward to your reply, thanks!

**Comment by Ino-Ichan** [comment]
@waveleaf27 
Hi. I'm extremely interested in your research. I'm also participating in the CVPR challenge and I would like to use the code right away for further research. Specifically, I'm interested in the part of training BEVFormer with Waymo Occupancy data. I would be grateful if you could send it to the following email: y.inoue@turing-motors.com
Thank you.

**Comment by jarvishou829** [comment]
> In order to make the code structure complete and readable, it takes some time to organize it. Currently, we only release the dataset and there is no time available to release the code. Feel free to contact me if you are in urgent need of the code .

Thanks for your great research on c2f solution on occupancy. I'm also trying to explore the c2f way to deal with this question and want to do some expirement. I would be grateful if you could share me with the c2f code [jarvishou@foxmail.com](jarvishou@foxmail.com)
Thank you.

**Comment by AMzhanghan** [comment]
Very exciting work! Could you share your source code for learning purposes? Thank you.  email：am.hankzhang@gmail.com

**Comment by AMzhanghan** [comment]
> In order to make the code structure complete and readable, it takes some time to organize it. Currently, we only release the dataset and there is no time available to release the code. Feel free to contact me if you are in urgent need of the code .

Very exciting work! Could you share your source code for learning purposes? Thank you. email：[am.hankzhang@gmail.com](mailto:am.hankzhang@gmail.com)

**Comment by waveleaf27** [comment]
@1349949 please see this request.

**Comment by AMzhanghan** [comment]
”Feel free to contact me if you are in urgent need of the code .“ ， 回复了又删掉 是啥意思，你这格局也就芝麻大小啊

**Comment by waveleaf27** [comment]
The code has been released, and in the upcoming period, our team members will re-organize the code and improve the readability.

**Comment by waveleaf27** [comment]
The code and model has been released in the ‘code’ branch for both Nuscene and Waymo dataset . We will further improve code quality.

**Comment by waveleaf27** [comment]
see the 'code' branch, update last work @Smarome

**Comment by RONINGOD** [comment]
> 

But I not find auto-labeling preprocessing script in this branch, will you release this code?

**Comment by RONINGOD** [comment]
> see the 'code' branch, update last week @Smarome

But I not find auto-labeling preprocessing script in this branch, will you release this code? @waveleaf27

**Comment by waveleaf27** [comment]
At present, the code used for ground-truth (GT) construction will not be released. This decision was made to prevent challenge participants from using scripts to generate their submissions.
The repo only contain the model code.
